services:
  server:
    image: mqsr/v2g-server:1.0.0
    ports:
      - "8080:8080"
    env_file:
      - configs/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}